---
--- Generated by Luanalysis
--- Created by DELL.
--- DateTime: 2022/10/18 15:49
---
--- 过程: 查询锁的值(uuid) --> 与自己的uuid对比 --> 正确解锁(返回true) , 错误退出(返回false
--local cacheUUID = getUUIDByLockKey(KEYS[1])
--if(cacheUUID == ARGV[1])then
--    if(0 == redis.call('del' , KEYS[1]))then
--        return false
--    else
--        return true
--    end
--else
--    return false
--end
--function getUUIDByLockKey(lockKey)
--    return redis.call('get' , lockKey)
--end
if(redis.call('get' , KEYS[1]) == ARGV[1])then
    redis.call('del' , KEYS[1])
    return true
end
return false